import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { DoptProvider, useDopt, withDopt, Blocks } from "@dopt/react";

function DocumentationBlock() {
  const [{ active, started }, { complete, start }] = useDopt(
    "ZVSR64jQC7cM6TAjOl79V"
  );
  if (active && !started) {
    start();
  }

  return (
    active && (
      <a onClick={complete} className={styles.card}>
        <h2>Documentation &rarr;</h2>
        <p>Find in-depth information about Next.js features and API.</p>
      </a>
    )
  );
}

function LearnBlock() {
  const [{ active }, { complete }] = useDopt("cDMdbFr0YAqXXIvv0INyq");

  return (
    active && (
      <a onClick={complete} className={styles.card}>
        <h2>Learn &rarr;</h2>
        <p>Learn about Next.js in an interactive course with quizzes!</p>
      </a>
    )
  );
}

function FindYourNextFriends({ block, methods }) {
  return (
    block.active && (
      <a onClick={methods.complete} className={styles.card}>
        <h2>Find Friends &rarr;</h2>
        <p>Join our shitty social network to find your next set of friends!</p>
      </a>
    )
  );
}

const FindYourNextFriendsWithDopt = withDopt(
  FindYourNextFriends,
  "sBrBcVyhPMyo4MMVs2rcK"
);

export default function Home() {
  /*
  const blocks: Blocks = {
    ZVSR64jQC7cM6TAjOl79V: {
      active: false,
      started: false,
      completed: false,
      stopped: false,
      exited: false,
      uuid: "ZVSR64jQC7cM6TAjOl79V",
    },
    cDMdbFr0YAqXXIvv0INyq: {
      active: false,
      started: false,
      completed: false,
      stopped: false,
      exited: false,
      uuid: "cDMdbFr0YAqXXIvv0INyq",
    },
    sBrBcVyhPMyo4MMVs2rcK: {
      active: true,
      started: false,
      completed: false,
      stopped: false,
      exited: false,
      uuid: "sBrBcVyhPMyo4MMVs2rcK",
    },
  };
   */

  return (
    <DoptProvider
      userId="9083778098"
      apiKey="6ce6801dfe4a3c8d20ed410b6acddd4d017f1a851a93d6633a8bc5e27a63c753_55"
    >
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <DocumentationBlock />
            <LearnBlock />
            <FindYourNextFriendsWithDopt />
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </DoptProvider>
  );
}
